language: node_js
node_js:
- node
- '5.11'
- '4.4'
- iojs
- '0.12'
matrix:
  fast_finish: true
sudo: false
before_script:
- npm run typings
script:
- npm run ci
before_deploy:
- npm run build
deploy:
  provider: npm
  email: simon@simonemms.com
  on:
    all_branches: true
    tags: true
    repo: riggerthegeek/steeplejack-bunyan
  api_key:
    secure: mNBycuVfDpAE6++cZzJKZeYkJ8EyrhkSQZsavopzIzE3yP3tzw30yh4zp9cejVaXrU0HMm8vyzFfEIZ7OfVHuhJwYBr9NzQtj7xZSD9HyDquGwGgwe58dIxcAPYlUARWhF5GS++o/Ps1+R9avwzEvYOE2z4L3QotuXIPnJusjQOdIQJhjlffc7oH6DPVh6AQ5vY2VdvILISkl7fCigWOgVwRd7Ak2eVh/nz9a75mc2HVQbViX4utvc8TiVGH5F45nyERYKOIIkW9rbzunatyzq7pgYjFljRixS4FSHa117FduOnQrwB4Wg69DXMHjzVnlmIXuyVCbqKlwc5QiZSUNK3vRZoARqt9OIUrdM8iMjxd8NQFWmupCsZLpOc7gBoQXbk9HzJ6P4qL/iiYRqwAYqO4BtM7WohUO6UGrJ3YcTRJGDWsN5MC71muIm6534gxAsLg25d+3890wOFbIYXBvncpdbfca8WJtqZPiccRYnwSMVYxCBAQD44JmN/ApHs4mPrYsv1y7lTFEVWpvVDo6r9fWl3w0XZCQQ8VzMi7nMPNfpyaKniYQYiZz2l7xy+o8Zp12A2/0OOwAjFYnXVUwHpxAIy0SUn42YJF21tth75eb+GD3fWR2DA4+EKszHIBTAH1KmNPOrLBvKe+0Q6vkG3fhVEuh3hO6Qa/eAaC5f0=
