language: node_js
node_js:
- '0.12'
- '0.11'
- '0.10'
- iojs
matrix:
  fast_finish: true
before_install:
- npm install -g grunt-cli
script:
- grunt ci
deploy:
  provider: npm
  email: simon@simonemms.com
  on:
    all_branches: true
    tags: true
    repo: slash-dev-slash-null/steeplejack-bunyan
  api_key:
    secure: UFMPhH+DjFTTArSNKoY/Cr0cBj2+EpKdga8OumGuuSKtByBCe80LWMWjZSAB2FOqfrr+bd1RJMIKOe+BxFfjlop3wrRmMFKcLLxK26ETYSdnOA3Sv+PDW+4XILMGgkraZVSoUVLfDhLuCzejNZD52NMNNJ2g+Mt8euIunguHXivSrnIjGIsKo28COs0Jyi6DNyp63Fr0UZFXeytdLR+YRjDTpJmxUrD8a9+xLWVs35X27gCTAvc4LIjt03TNYhPW1LIsj6+F5s0JMtZzCaowQ1hTFZhMI51ZtT6uD+Xm3xHPPKLrodufo8PcuTeginATxhz1imqkcpXVHFzcl0uLoc2qP76K4SmWcvCewEX25l46dRBLyzxZHzNM4xBsK5rYCk21C6if06PTY77iokjuW+O5jyhC9SjBOj4HYCWQTGutRksE7Cfv6BikYBZidIv4vlMvWDApG/QH7FEe88JFRm8cvUjbn+bJIpIXHHC30xFgYpLz9jRnp9/ob2ZUTLOksg6pE4T1Sx0qrUy9yVkqgZI7vttqbsgEJ0EbkryVlFiA41doKZeQ9U29Z4fIPujQXhoGVEOhp73Kqg0IXHC2c0A9x//1MQr9HO6chNMiDDKTm5Mi+L7Gv24uNboo96yPf1AGzn09di3c25iQwKwWb++g2fEpJhKfq3F0sivOd94=
